# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4634c90f2622c0b95bac1478dbb873bae2ddb7f0af900d2df08600903de0b9d27a53f0abebf0e1237e880be51a219dddd077717e7e98cd5a7b05fbf57c3b938

test:
  secret_key_base: 73ffa9ba00001b733220fee91d351afcb91f35e57d8b0041a13b2d553c0d5f9688b18cae99f09f73f324ea3744e036bf1435bf5f13365fd225f332317382f6cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
